2023-09-03 09:02:29:229 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:02:56:256 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:03:15:315 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:03:43:343 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:03:58:358 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:04:03:43 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:04:08:48 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:04:10:410 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:02:52 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:08:58 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:11:511 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:13:513 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:15:515 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:19:519 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:20:520 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:46:546 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:49:549 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:05:50:550 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:07:04:74 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:07:07:77 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:10:30:1030 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:10:32:1032 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:10:53:1053 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:23:1223 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:29:1229 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:38:1238 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:40:1240 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:42:1242 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:49:1249 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:12:51:1251 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:14:08:148 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:08:148 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:08:148 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:12:1412 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:12:1412 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:16:1416 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:16:1416 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:19:1419 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:19:1419 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:24:1424 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:24:1424 [31merror[39m: [31mError dropping the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:14:30:1430 [31merror[39m: [31mError altering the database: could not open relation with OID 446523[39m
2023-09-03 09:14:45:1445 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:15:10:1510 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:15:17:1517 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:15:21:1521 [31merror[39m: [31mError altering the database: could not open relation with OID 446560[39m
2023-09-03 09:15:23:1523 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:15:42:1542 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:16:06:166 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:17:39:1739 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:17:45:1745 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:17:47:1747 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:22:37:2237 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:22:37:2237 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:25:08:258 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:25:08:258 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:25:11:2511 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:25:11:2511 [31merror[39m: [31mError altering the database: could not open relation with OID 446624[39m
2023-09-03 09:27:06:276 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:27:06:276 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:27:08:278 [31merror[39m: [31mError altering the database: could not open relation with OID 446633[39m
2023-09-03 09:27:12:2712 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:27:12:2712 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:27:38:2738 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:27:38:2738 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:27:41:2741 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:27:41:2741 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:05:285 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:05:285 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:10:2810 [31merror[39m: [31mError altering the database: could not open relation with OID 446679[39m
2023-09-03 09:28:13:2813 [31merror[39m: [31mError altering the database: could not open relation with OID 446688[39m
2023-09-03 09:28:19:2819 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:19:2819 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:21:2821 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:21:2821 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:23:2823 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:28:26:2826 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:26:2826 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:37:2837 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:28:37:2837 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:28:39:2839 [31merror[39m: [31mError altering the database: could not open relation with OID 446742[39m
2023-09-03 09:28:39:2839 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:30:07:307 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:30:09:309 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:30:17:3017 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:30:19:3019 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:30:19:3019 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:31:48:3148 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:32:05:325 [31merror[39m: [31mError altering the database: could not open relation with OID 446797[39m
2023-09-03 09:32:05:325 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:32:07:327 [31merror[39m: [31mError altering the database: could not open relation with OID 446816[39m
2023-09-03 09:32:08:328 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:33:11:3311 [31merror[39m: [31mUnable to connect to the database:  SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string[39m
2023-09-03 09:33:13:3313 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:33:14:3314 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:33:23:3323 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:33:25:3325 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:33:40:3340 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:33:42:3342 [31merror[39m: [31mError altering the database: could not open relation with OID 446861[39m
2023-09-03 09:34:03:343 [31merror[39m: [31mUnable to connect to the database:  SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string[39m
2023-09-03 09:35:02:352 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:35:30:3530 [31merror[39m: [31mError altering the database: No description found for "users" table. Check the table name and schema; remember, they _are_ case sensitive.[39m
2023-09-03 09:35:40:3540 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:35:40:3540 [31merror[39m: [31mError altering the database: ConnectionManager.getConnection was called after the connection manager was closed![39m
2023-09-03 09:35:43:3543 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:35:43:3543 [31merror[39m: [31mError altering the database: could not open relation with OID 446889[39m
2023-09-03 09:35:48:3548 [31merror[39m: [31mError altering the database: Validation error[39m
2023-09-03 09:37:03:373 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:37:03:373 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:41:26:4126 [31merror[39m: [31mError altering the database: Validation error[39m
2023-09-03 09:41:26:4126 [31merror[39m: [31mError altering the database: could not open relation with OID 446908[39m
2023-09-03 09:43:15:4315 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:43:15:4315 [31merror[39m: [31mError altering the database: relation "users" does not exist[39m
2023-09-03 09:43:18:4318 [31merror[39m: [31mError altering the database: Validation error[39m
2023-09-03 09:43:48:4348 [31merror[39m: [31mError altering the database: Validation error[39m
