export const __esModule: boolean;
export const Exception: typeof exceptions_1.Exception;
export const AuthenticationException: typeof authentication_exception_1.AuthenticationException;
export const BadRequestException: typeof badRequest_exception_1.BadRequestException;
export const ForbiddenException: typeof forbidden_exception_1.ForbiddenException;
export const InternalServerException: typeof internalError_excpetion_1.InternalServerException;
export const NotFoundException: typeof notFound_exception_1.NotFoundException;
export const ConflictException: typeof conflict_exception_1.ConflictException;
export const ValidationException: typeof validation_exception_1.ValidationException;
import exceptions_1 = require("./exceptions");
import authentication_exception_1 = require("./authentication.exception");
import badRequest_exception_1 = require("./badRequest.exception");
import forbidden_exception_1 = require("./forbidden.exception");
import internalError_excpetion_1 = require("./internalError.excpetion");
import notFound_exception_1 = require("./notFound.exception");
import conflict_exception_1 = require("./conflict.exception");
import validation_exception_1 = require("./validation.exception");
